### ISSUE TITLE
Loginscreen

### ISSUE THREAD

**Issue by olyaee** [amosproj/amos-ss2021-carbon-footprint#10]
## User story
1. As a Siemens employee
2. I need a way to log in with my Siemens MyID account
3. So that I get access to the Carbon Footprint application

## Acceptance criteria
* [x] There is a field where I can enter my e-mail address and a second field for the password
* [x] There is a "Login"-Button which can be pressed
* [x] There is a "Forgot password?"-Button, which directs to the "password forgotten"-page
* [x] This page is the first one shown when the application is started
* The connection to Siemens MyID should not be done (yet)

## Definition of done

- [x]  Documentation for that feature is done
- [x]  Feature branch has been merged
- [x] Code has been reviewed by at least one other team member
- [x] Unit tests are written

![Frame 40](https://user-images.githubusercontent.com/13171558/119489341-e2d1b580-bd5b-11eb-88bf-33056e49aaf9.png)

**Comment by gandompm** [comment]
I would like to start doing this task this week with react if you all agree. 
although the UI is not yet designed and the industry partner has not given the API. 
but there is so much to do with the login page. 
creating a simple login form using bootstrap and handling events on the input fields and login submit button. 
making components reusable, proper validation rules (using Joi library)  for the fields, and displaying validation errors. 

then in the next weeks, when the UI and API are ready and we can simply change the UI and send the data to the server.
