### ISSUE TITLE
Close comparison buttons

### ISSUE THREAD

**Issue by olyaee** [amosproj/amos-ss2021-carbon-footprint#101]
## User story
1. As a salesperson
2. I want to have a button to go back to the details page from the comparison page
3. So that I see the product details

## Acceptance criteria
* [x] At the comparison view, there is one button for every scenario
* [x] After clicking this Button, the coresponding scenario is closed
* [x] Button matches the uniform interface of the software
* See picture in comments

## Definition of done
* [x] Documentation for the feature is done
* [x] Feature branch has been merged
* [x] Code has been reviewed by at least one other team member
* [x] Unit tests are written

**Comment by MichaelScheiderer** [comment]
![Close Buttons](https://user-images.githubusercontent.com/82509508/122364273-e8d14580-cf59-11eb-8735-8d45e096e21e.png)

**Comment by IremToroslu** [comment]
![image](https://user-images.githubusercontent.com/29985277/122764961-4dfda180-d2a0-11eb-93ad-c68affb9184b.png)

pls kindly find  the current look and feel of the close buttons 😄

**Comment by IremToroslu** [comment]
@ScoutAtlas I just reconfigured the buttons that we worked on. I removed the "close" text, I guess we do not need one.

**Comment by IremToroslu** [comment]
@Waldleufer , now we have space between buttons as well. It turns out to be a mouse cursor pointer once you hover the related button. It applies for each button , I fixed them all. 😄
