### ISSUE TITLE
"Forgot password"-Screen

### ISSUE THREAD

**Issue by olyaee** [amosproj/amos-ss2021-carbon-footprint#11]
## User story
1. As a Siemens employee
2. I need to be able to reset my password
3. So that I can get access to the application in case that I forgot my password

## Acceptance criteria
* [x] There is a field where I can enter my E-Mail
* [x] There is a button "Recover password" which can be pressed
* [x] There is a link back to the login page
* The connection to Siemens MyID should not be done (yet)

## Definition of done
* Documentation for that feature is done
* Feature branch has been merged
* Code has been reviewed by at least one other team member
* Unit tests are written

![Frame 41](https://user-images.githubusercontent.com/13171558/119490192-dbf77280-bd5c-11eb-8e33-7ed5747dd50f.png)

**Comment by manifau** [comment]
Please feel free to review :)

![image](https://user-images.githubusercontent.com/82512645/122947495-7d80dc80-d37a-11eb-86fe-940a0c57bd0d.png)
