### ISSUE TITLE
Fixing and resizing  DetailsPage and Mydashboard page

### ISSUE THREAD

**Issue by ScoutAtlas** [amosproj/amos-ss2021-carbon-footprint#137]
- [x] ClassName of PieChart causes it to overlap
- [x] Overlapping of ColumnChart and Table
- [x] resize the card components 
- [x] reconfiguration of the chart components

`return (
        <div className='ChartItems' id='chart'>
            <ReactApexChart options={options} series={series} type='donut' />
        </div>
`

## Description
The class ChartItems causes PieChart to overlap

**Comment by Waldleufer** [comment]
@ScoutAtlas In which branch does this occur? How did it occur? It doesn't happen in the current main branch for me.
