### ISSUE TITLE
Change variables and update graphs

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#17]
## User story
1. As a salesperson
2. I need to change the variables of a product/select different scenarios
3. So that I can compare different scenarios and show the customer the impact of switching to another scenario

## Acceptance criteria
* [x] After changing the variable/scenario the graph is automatically updated
* [x] All the available scenarios are shown in the dropdown menu

## Definition of done
* [x] Documentation for the feature is done
* [x] Feature branch has been merged
* [x] Code has been reviewed by at least one other team member
* [x] Unit tests are written

**Comment by olyaee** [comment]
<img width="704" alt="Screenshot 2021-05-03 at 20 36 23" src="https://user-images.githubusercontent.com/13171558/116917662-3bc39780-ac4f-11eb-9eeb-ecbf0f46f2b5.png">
