### ISSUE TITLE
Add second canvas

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#18]
## User story
1. As a salesperson
2. I need to have two windows (canvases) beside each other and visualize two scenarios alongside each other
3. So that I can show the comparison to the costumer

## Acceptance criteria
* [x] After pressing "Add" the default canvas has to be divided into two canvases
* [x] The second canvas shows the baseline scenario of the same model as default
* [x] Graphs are automatically realigned 
* [x] Graphs are automatically resized 
* [x] Implemented in a way that it is possible to divide the canvas into more than two. However, currently, we just need to compare two scenarios

**Comment by olyaee** [comment]
<img width="784" alt="Screenshot 2021-05-04 at 21 54 55" src="https://user-images.githubusercontent.com/13171558/117062136-5ebf7b80-ad23-11eb-838c-881153fb9d09.png">

**Comment by Waldleufer** [comment]
> Hi 😊 
> since this week we wanted that at first only one person to be assigned to a task and others review and develop it further.
> regarding issue #18, which I was assigned, these are some features that are already implemented(please checkout branch #18 and have a look), and also some features that should be implemented.
> such as:
> #### User Interface Issues:
> 1. as @Waldleufer in the comments #42  has mentioned, the two drop-down buttons in comparing canvas page, should be better visualized and be separated.
> 	Martin suggested using two columns as in the "CanvasCompareComponent" page, for each dropdown button.
> 2. feel free to change the UI, if you find it more beautiful that way. (as @IremToroslu is also working on this - #37 ).
> ####  Logic Issues:
> 1. I have converted back the "DetailsComponent" to a class. because it needs to store the boolean variable which indicates whether the "DetailsComponent" is a Compare page or not.
> 	now we are facing the issue that apparently our storing management architecture, is not compatible with Class components.
> 	right now we only receive one variable from its parent. I have commented this line, but It should be fixed (we should be able to get props from its parent.)
> 2. if you see the code, I have defined a new component called "CompareCanvasComponent". this component will be called inside "CanvasComponent" if the props("loadComparePage") that it receives is set to true.
> it would be nice if we also create a new component maybe called "CompareSelectVariable" inside "SelectVariableComponent" and clean this component.
> 3. in Kanban board there is an Acceptance criterion which is:
> Implemented in a way that it is possible to divide the canvas into more than two. However, currently, we just need to compare two scenarios.
> 4. ...
> #### there are also some issues that are time-consuming:
> 1. making the canvas screen compatible with different screen sizes.
> 
> Note: I am probably not able to work on the project in the next 2 days. but after that, I will also try to implement these issues.
> \- @gandompm 

Crossposting from Slack

**Comment by Waldleufer** [comment]
> I have converted back the "DetailsComponent" to a class. because it needs to store the boolean variable which indicates whether the "DetailsComponent" is a Compare page or not.
now we are facing the issue that apparently our storing management architecture, is not compatible with Class components.
right now we only receive one variable from its parent. I have commented this line, but It should be fixed (we should be able to get props from its parent.)

I will have a look at that! I'm sure I can figure that out.

**Comment by Waldleufer** [comment]
done. Just a little sidenote: functions can also define a state, using hooks 😊

**Comment by gandompm** [comment]
> done ([64e711b](https://github.com/amosproj/amos-ss2021-carbon-footprint/commit/64e711bcdda00a20b1639d41513459159c2a867a)). Just a little sidenote: functions can also define a state, using hooks 😊

Perfect 👍

**Comment by Waldleufer** [comment]
> in Kanban board there is an Acceptance criterion which is:
Implemented in a way that it is possible to divide the canvas into more than two. However, currently, we just need to compare two scenarios.

It is technically possible to display more than two Compare Canvases on one page. However, it might not be very practical.
