### ISSUE TITLE
Basic UI Design

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#20]
## User story
1. As a Software Developer
2. We need a basic UI design created in https://www.figma.com/
3. So that the website looks attractive for the industry partners

## Acceptance criteria
* Criterion 1
* Criterion 2
* ...

**Comment by Waldleufer** [comment]
@olyaee you said you already have some info / a project at figma, could you maybe share that project here again?

**Comment by olyaee** [comment]
Here you can request an education account
https://www.figma.com/education/

I have made a project and put some templates that might be relevant to our needs.
There are much more in the Figma community 
https://www.figma.com/file/IMQ0L5JfTWtP8cNyXSlQz4/Carbon-Footprint?node-id=15%3A194

After creating the component and selecting it, you can select "Inspect" in the right panel and see the CSS code for it.

**Comment by Waldleufer** [comment]
Also to be considered:

> https://github.com/tabler/tabler
> @ScoutAtlas 

https://preview.tabler.io/

**Comment by Waldleufer** [comment]
And:
> [UI / UX Design Tutorial – Wireframe, Mockup & Design in Figma](https://www.youtube.com/watch?v=c9Wg6Cb_YlU)
> @SaiVarunVaranasi

**Comment by Waldleufer** [comment]
Created a Landing Page and a Dashboard while learning Figma.

[Proj8 Figma Team Project](https://www.figma.com/file/BTGl7CJIXj4mVxlTIjTImH/Carbon-Footprint-Visualizer?node-id=0%3A1)
