### ISSUE TITLE
Decide about final frontend Framework

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#21]

**Comment by Waldleufer** [comment]
Some Information regarding that that possibly would be nice to have here:

> In terms of frontend development frameworks, as far as i know there are some frameworks that can build frontends that you can use on web and mobile alike. These are React Native (from Facebook, that we already talked about), Xamarin (from Microsoft) and Flutter (from Google). I think React Native ist the most used atm, so probably a good choice. 
> @MartinDuersch

**Comment by Waldleufer** [comment]
> Agree with you for the Frontside Framework
> @gandompm

**Comment by olyaee** [comment]
@gandompm Parham, I know you have done a lot of research about react-native. Could you please have a loot at React expo as well, and see if it makes easier coding what we need?

**Comment by gandompm** [comment]
@olyaee merci Ehsan for your comment. honestly, I don't have so much to say about React expo. I should do research about it. I hope that I can do it till tomorrow's meeting.  
last week I concluded that learning react is inevitable for a web developer, so in the last two days, I started learning it and didn't do research.
