### ISSUE TITLE
Decide about final backend Framework

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#22]

**Comment by olyaee** [comment]
I have heard that [Django](https://www.djangoproject.com/) is also popular and its language is python. You might want to consider.

**Comment by Waldleufer** [comment]
Some further info in regards to this:

> In terms of Backend, I suggest using .net Core because it brings frameworks for everything we need (API controllers, database, security authentication etc.) and it's very easy to host this app on a cloud provider like Azure. I know that Siemens themselves heavily use Azure and even the API that we got to work with is hosted on Azure.
> ![ae8a5b43-8cd7-4759-9271-648a58700ce0](https://user-images.githubusercontent.com/22003632/115829296-1c3a9c80-a40f-11eb-9458-3bf277f7fa98.jpg)
> @MartinDuersch

**Comment by Waldleufer** [comment]
> For backend, I prefer to remain on JavaScript
> @gandompm
