### ISSUE TITLE
Receive data from SimaPro API

### ISSUE THREAD

**Issue by olyaee** [amosproj/amos-ss2021-carbon-footprint#27]
## User story
1. As a software developer
2. I need to receive Siemens Energy projects, products, and models from SimaPro API
3. So that I can structure and show them to the user

## Acceptance criteria
* I receive data of currently available projects created by Siemens Energy

**Comment by Waldleufer** [comment]
![image](https://user-images.githubusercontent.com/22003632/117122204-ec3bb380-ad95-11eb-8660-fc42488fc232.png)

> Hey, since there is still a lot of confusion about how the structure of the app is supposed to look in the end i decided to draw the structure of what we are supposed to do as I understand it right now.
>
> Apparently we only want to have Siemens MyID users to have access to the app.
>
> since Siemens MyID and SimaPro are (by the looks of it) two different account systems I guess we will use some kind of "service account" (like the one Ehsan gave us) to access the SimaPro API. If we were to include the SimaPro API service account credentials in the frontend, the user could just read the service account credentials in the browser (since everything that's happening in the frontend can be looked into). So we need to have the login process via credentials happening in the backend. The resulting token could then maybe be given to the frontend, so that the frontend could do its own requests directly to the SimaPro API. Note that a user could then just take the token and use it to do everything the SimaPro API offers, so that may be a risk, but I guess we expect the user to be verified as SIemens MyID user at that point anyway so I dont know whether that is fine or not.
>
> This is just my guess of what it's supposed to look like from the scattered information we got from Siemens so far so if I missed some information please comment
> @MartinDuersch 

> Thats mostly what I also thought. Except giving the token to the frontend. As you said, the user would theoretically be able to do everything the API offers. Since we need to implement access rights, so its possible to decide which user can see which content, I think it wouldnt be good if the user could get access to the token. The only solution would be, as far as I get it, to use the backend between every request.
> @MichaelScheiderer 

Just cross-posting critical information for this Backend Task here so that it can be found easily, don't mind me 🐈 (Slack Discussion Content)

**Comment by Waldleufer** [comment]
@MartinDuersch 

We need to find out how Siemens MyID and SimaPro API Id's work / correspond. 

- Where to get information about the role that different users get? Admin? Normal User?
- Does The Siemens MyID Token have any role information. / Does the SimaPro API Token have any role information that we can base our role system on.
- Or are these roles to be handled on our side?
- Does every Siemens MyID User have a linked SimaPro Account?

- In which way do we need to worry about access rights to the data?

**Comment by olyaee** [comment]
As far as I got from the meeting with the SimpaPro expert, We need only one account for SimaPro API and its token is used for all further requests. SimaPro API supports multiple requests at the same time. Therefore we don't need a SimaPro account for each user. @gandompm Correct me if I'm wrong.

**Comment by Waldleufer** [comment]
But they did not give us any information about role management yet. @MartinDuersch Correct me if I'm wrong. 
And no information about the Siemens MyID Tokens. 

- Will only Siemens MyID Users have access to the application or do we need to account for other users as well? Which rights are they going to have?

We were also talking about security concerns in our SD Meeting, but the other Martin has far more intel on that than I 😃 And he will probably be in touch with you @olyaee shortly ☺️
