### ISSUE TITLE
Visualize a scenario

### ISSUE THREAD

**Issue by olyaee** [amosproj/amos-ss2021-carbon-footprint#29]
## User story

1. As a user
2. I want to see the information of a scenario as graphs
3. So that I get structured and visual information about the scenario

## Acceptance criteria
* Includes two graphs and a table that looks like the graph and tables of the pdf that is given by the industry partner (the pdf exists in "Documents from Industry Partner" folder)

**Comment by Waldleufer** [comment]
The file with the detailed Information:

https://drive.google.com/drive/folders/1kM26KP8FQcds-y65TCeRtY5hToOF1uW9

**Comment by olyaee** [comment]
<img width="673" alt="Screenshot 2021-05-03 at 20 38 06" src="https://user-images.githubusercontent.com/13171558/116917839-788f8e80-ac4f-11eb-8cb3-4e239c0af264.png">
<img width="715" alt="Screenshot 2021-05-03 at 20 38 19" src="https://user-images.githubusercontent.com/13171558/116917867-8218f680-ac4f-11eb-88ef-02b6f9c3dbd6.png">
<img width="722" alt="Screenshot 2021-05-03 at 20 38 33" src="https://user-images.githubusercontent.com/13171558/116917896-89400480-ac4f-11eb-86bc-ebdf10b26705.png">
