### ISSUE TITLE
React.js initial setup

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#31]

**Comment by Waldleufer** [comment]
Apperently we meant React.js all the time (React Native -> Apps; React.js -> Website)

**Comment by ScoutAtlas** [comment]
Subtask:

- [ ] copy website structure from figma and realize it in react.js
- [ ] copy website look (colors, logos, icons, ...)

**Comment by Waldleufer** [comment]
> **Subtask:**
> 
> * [ ]  copy website structure from figma and realize it in react.js
> * [ ]  copy website look (colors, logos, icons, ...)

@ScoutAtlas 
I'd say that would be more than the initial setup, right? This rather sounds like _UI Customization_ or _UI Improvements_ or something like that. Maybe that could be an Item that could be added to the Backlog for one of the upcoming sprints? @olyaee @MichaelScheiderer

**Comment by Waldleufer** [comment]
and may I suggest the following to be added to this issue: @MichaelScheiderer 

## User story
1. As a developer
2. I need a working webpage infrastructure that I can work on
3. So that I can work on any other frontend task

## Acceptance criteria
- [ ] Working frontend infrastructure (A website that can be deployed locally by executing `yarn start`)

**Comment by MichaelScheiderer** [comment]
> In my opinion, the Issues e.g. "Navigate through different Categories..." or "Select a model..." are only solved, if the website it functional enough, that you can really navigate through the categories or select a model.
So these issues are supposed to "include" a working UI so far that you can do those things.
Imo things like "UI Improvements/Customization" can be done when the basic functionality works and are atm not that important.
I also thought about adding that user story, but I dont think that it belongs to the Kanban Board. According to the Slides, the Kanban Board should contain features like "I want to be able to navigate through the products". Then those features should be broken down by SDs into small tasks, which are then distrubuted to the single SDs (see C03 page 33). The small tasks should not be part of the Kanban board, since those are not really product features. (Imo also "React.js initial setup" should not be a standalone issue, since its a subtask that needs to be done to fulfill a "real" user story)

Crosspost from Slack

**Comment by Waldleufer** [comment]
> yeah, but it is a very complex subtask, on which all other upcoming frontend tasks relied on that's why it is there. imo the User Story just rectifies the Item being in the backlog and provides the information about when it is done (which it already is at this point as I would say). Because SDs worked on that, it needed doing and now its done.^

Slack Crosspost
