### ISSUE TITLE
Restructure GitHub branches and folder structure

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#36]
## Acceptance criteria
* The existing branches are merged and renamed to the following ones:
-- Release Branch
-- Main
-- Frontend-Dev
-- Backend-Dev

**Comment by ScoutAtlas** [comment]
Rework following index.html file for tab name, url references, etc.

https://github.com/amosproj/amos-ss2021-carbon-footprint/blob/ac9381d9c45b05d3699bbb5dd5624cdc4414a918/frontend/public/index.html#L1-L40

**Comment by Waldleufer** [comment]
> Rework following index.html file for tab name, url references, etc.
> 
> https://github.com/amosproj/amos-ss2021-carbon-footprint/blob/ac9381d9c45b05d3699bbb5dd5624cdc4414a918/frontend/public/index.html#L1-L40

I forgot to do this @ScoutAtlas -.-
