### ISSUE TITLE
Export graphs as docx

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#39]
## User story
1. As a salesperson
2. I want to be able to export graphs as a docx file
3. So that I can share them with my customers

## Acceptance criteria
* [x] Research about different libraries for generating and exporting pdfs is done and the best solution is found
* [x] The generated file looks like the example pdf (LPT_EPD_ISO14021.pdf)
* [x] There exists a button where I can press on to export/download the shown baseline scenario's graphs as a docx file
* [x] Code was moved to a separate component

## Definition of done
* [x] Documentation for that feature is done
* [x] Feature branch has been merged
* [x] Code has been reviewed by at least one other team member
* [x] Unit tests are written

**Comment by ScoutAtlas** [comment]
https://react-pdf.org/
Possible library?

**Comment by manifau** [comment]
https://stackoverflow.com/questions/59737202/is-there-a-way-to-convert-react-chartjs-2-chart-to-pdf (Might be helpful as well)

**Comment by olyaee** [comment]
Please find the template pdf (LPT_EPD_ISO14021-template.pdf) in the drive folder where I have removed graphs from it and you can place the graphs in their positions.

**Comment by ScoutAtlas** [comment]
- [ ] Implemented first version using: https://github.com/MrRio/jsPDF

**Comment by gandompm** [comment]
https://www.youtube.com/watch?v=1Vw-e_ex2S0 
I found a practical library which is called "KendoReact PDF Generator" and easy to implement. 
but unfortunately, it's not free. so I guess we can't use it.

**Comment by gandompm** [comment]
As I see it, we should export first a png file from the diagrams and then export them to pdf. do you agree? 
I will try to export an image from PieChart diagram and export it to pdf.

**Comment by olyaee** [comment]
<img width="727" alt="Screenshot 2021-06-30 at 13 56 29" src="https://user-images.githubusercontent.com/13171558/123956605-28ad1980-d9ab-11eb-8e9e-f8a2a643f575.png">

Please remove this lines from the import if possible
