### ISSUE TITLE
Compatibility with different screen sizes (especially mobile devices)

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#54]
## User story
1. As a salesperson
2. I want to be able to use the software on all kind of devices
3. So that I can have access to the software everywhere

## Acceptance criteria
* [x] The website should be displayed correctly on all kind of devices (Desktops, Laptops, Tablets, Smartphones)
* [x] The functionality (e.g. the side bar, pressing buttons, ...) should work on all devices

## Definition of done
* Documentation for that feature is done
* Feature branch has been merged
* Code has been reviewed by at least one other team member
* Unit tests are written

**Comment by ScoutAtlas** [comment]
Possible implementation?
https://medium.com/how-to-react/convert-your-existing-react-js-app-to-android-or-ios-app-using-the-ionic-capacitor-a127deda75bd

**Comment by manifau** [comment]
https://medium.com/@mustwin/responsive-react-9b56d63c4edc

**Comment by manifau** [comment]
https://www.npmjs.com/package/react-responsive
