### ISSUE TITLE
Details page not properly formatting (on different screen sizes)

### ISSUE THREAD

**Issue by MichaelScheiderer** [amosproj/amos-ss2021-carbon-footprint#84]
## Description

On some screensizes the details page is not displayed correctly.

## Expected Behavior

The details page and the graphs on that page should be displayed correctly (It's possible to see the content of the graphs, no texts or graphs are outside the box).

## Actual Behavior

Text and graphs are outside the box.
![image](https://user-images.githubusercontent.com/82509508/120610456-78073500-c453-11eb-92ed-4919bdce8686.png)

## Steps to Reproduce

1. Resize the details page (e.g. to 555x1133)

## Your Environment

* Version used: sprint-07-release
* Browser Name and version: Chrome 90.0.4430.212
* Operating System and version (desktop or mobile): Windows 10

**Comment by Waldleufer** [comment]
- [ ] PieChart not staying within bounds.
- [ ] Header height is not correctly set.
- [ ] No Spacing between the columns
- [ ] Adding a White Background box to the case where only one scenario is shown.
- [ ] Unique Margins and Paddings in different places

**Comment by IremToroslu** [comment]
Please kindly find the some changes regarding this issue on the #78 branch as well. 😄

**Comment by manifau** [comment]
![image](https://user-images.githubusercontent.com/82512645/121819515-c73c3980-cc8d-11eb-9790-b380733ecc7f.png)
![image](https://user-images.githubusercontent.com/82512645/121819545-f05cca00-cc8d-11eb-9965-9c67be6026c6.png)

I really liked the solution to divide the table into two for smaller screens. It looks awesome!!
Just a very small remark on the alignment of the two tables which is slightly inwards for the second one :)

**Comment by IremToroslu** [comment]
Looks great 😄

**Comment by Waldleufer** [comment]
Thank you! 

as to:

> ![image](https://user-images.githubusercontent.com/82512645/121819515-c73c3980-cc8d-11eb-9790-b380733ecc7f.png)
> ![image](https://user-images.githubusercontent.com/82512645/121819545-f05cca00-cc8d-11eb-9965-9c67be6026c6.png)
> 
> I really liked the solution to divide the table into two for smaller screens. It looks awesome!!
> Just a very small remark on the alignment of the two tables which is slightly inwards for the second one :)

I wasn't able to handle every edge case, and if the styling should be different we can change it later always. My main concern was to get it working properly. And you may have noticed: for the rare cases where the tables don't fit in their column I made them scrollable so that they still work in these cases. 🙂
